internal social network/bt15/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'users#index'

  scope '/:locale' do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    resources :users do
      # collection do
      #   get :signin
      #   get :register
      # end
    end
    # get '/login', to:'users#login'
    get '/register', to: 'users#new'

    # resources :static_pages do
    #   collection do
    #     get :home
    #     get :help
    #   end
    # end
    # get '/home', to: 'static_pages#home'
    # get '/help', to: 'static_pages#help'

    # get 'static_pages/home'
    # get 'static_pages/help'
    resources :microposts
    resources :account_activations, only: :edit
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :password_resets, only: %i[new edit update create]
end

internal social network/bt15/app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  belongs_to :user
  validates  :content, presence: true
  self.per_page = 5
end

internal social network/bt15/app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[show edit update destroy]
  skip_before_action :redirect_to_users

  # GET /microposts or /microposts.json
  def index
    @content = params[:content]
    @microposts = (if @content.present?
                     Micropost.where('content LIKE ?',
                                     "%#{@content}%")
                   else
                     Micropost.all
                   end).paginate(page: params[:page])
  end

  # GET /microposts/1 or /microposts/1.json
  def show; end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
    unless current_user.admin || current_user?(@micropost.user)
      redirect_to microposts_path
      flash[:danger] = t 'You must be admin or this user'
    end
    @edit = true
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        flash[:success] = t 'Micropost was successfully created'
        format.html { redirect_to @micropost }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        flash[:success] = t 'Micropost was successfully updated'
        format.html { redirect_to @micropost }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      flash[:success] = t 'Micropost was successfully destroyed'
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_micropost
    @micropost = Micropost.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def micropost_params
    params.require(:micropost).permit(:user_id, :content)
  end
end

internal social network/bt15/app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
  def author_of_micropost?(userId)
    user = User.find_by(id: userId)
    @user  = user
  end
end

internal social network/bt15/app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @edit %>
      <div class="form-group">
        <%= form.label I18n.t('microposts.user_Id') + ": #{ @micropost&.user.id} "  %>
        <%= form.hidden_field :user_id, :value => @micropost&.user.id , class: "form-control" %>
    </div>
    <% else %>
    <div class="form-group">
        <%= form.label I18n.t('microposts.user_Id') + ":#{current_user.id} "  %>
        <%= form.hidden_field :user_id, :value => current_user.id , class: "form-control" %>
    </div>
  <% end %>


  <div class="field">
    <%= form.label  I18n.t('microposts.content')  %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

   <div class="actions">
    <%= form.submit I18n.t('actions.submit'), class: "btn btn-primary" %>
  </div>
<% end %>

internal social network/bt15/app/views/microposts/edit.html.erb
<% provide :title, "Edit Micropost" %>

<h1><%= I18n.t('microposts.edit micropost') %></h1>

<%= render 'form', micropost: @micropost %>
<%= link_to I18n.t('actions.show'), @micropost %> |
<%= link_to I18n.t('actions.back'), users_path %>

internal social network/bt15/app/views/microposts/index.html.erb
<%=javascript_include_tag('manager/micropost.js') %>

<% provide :title, "Microposts" %>
<h1><%=I18n.t("microposts.title") %></h1>

<table id="example" class="table table-striped">
  <thead>
    <tr>
      <th style="margin:5px"><%=I18n.t("microposts.user_Id") %></th>
      <th> <%=I18n.t("microposts.content") %></th>
      <th> <%=I18n.t("microposts.author") %></th>
      <th> <%=I18n.t("microposts.create_at") %></th>
      <th colspan="3" style="text-align:center;"><%=I18n.t("microposts.actions") %></th>
    </tr>
  </thead>

  <tbody>
   <%= link_to '<button class="btn btn-primary"> <i class="fa fa-plus"></i> </button>'.html_safe , new_micropost_path %>
     <div style="justify-content: flex-end; display: flex;" > 
        <div class="form-outline">
          <input type="search" id="form1" name="content" placeholder=<%= I18n.t("actions.search content")%> class="form-control content" />
        </div>
          <a href=<%= microposts_path	%> class="btn_search"> 
            <button type="button" class="btn btn-primary-color">
              <i class="fa fa-search"></i>
            </button>
          </a>
      </div>
  
    <% @microposts.each do |micropost| %>
      <tr >
        <td><%= micropost.user_id %></td>
        <td><%= micropost.content %></td>
        <td>
          <% if author_of_micropost?(micropost.user_id) %>
             <%= @user.name %>
          <% end %>
         </td>
         <td>
           <%= micropost.created_at %>
        </td>
     

        <td>
          <%= link_to '<button class="btn btn-success"> <i class="fa fa-info-circle"></i> </button>'.html_safe , micropost, style: 'color:#FFFFFF' %>
        </td>

        <td>
          <% if current_user&.admin ||  current_user?(@user) %>
                <%= link_to '<button class="btn btn-info"> <i class="fa fa-edit"></i> </button>'.html_safe , edit_micropost_path(micropost), style: 'color:#FFFFFF' %>
          <% end %>  
        </td >

         <td>
           <% if current_user&.admin ||  current_user?(@user) %>
             <%= link_to '<button class="btn btn-danger"> <i class="fa fa-trash"></i> </button>'.html_safe , micropost, method: :delete, data: { confirm: 'Are you sure?' }, style: 'color:#FFFFFF' %>
           <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div style="justify-content: center;display: flex;"> 
  <%= will_paginate @microposts %> 
<div>

<script>
$('.btn_search').on('click', function(){
  content = $('.content').val();
  location.href ="<%= microposts_path %>"+"?content=" + content
});
</script>

internal social network/bt15/app/views/microposts/new.html.erb
<% provide :title, "New Micropost" %>

<h1><%= I18n.t('microposts.new micropost') %></h1>

<%= render 'form', micropost: @micropost %>

<a href=<%= microposts_path %>><%= I18n.t("actions.back")%></a>

internal social network/bt15/app/views/microposts/show.html.erb
<% provide :title, "Show Micropost" %>
<p>
  <strong><%= I18n.t("microposts.user_Id")%></strong>
  <%= @micropost.user_id %>
</p>

<p>
  <strong><%= I18n.t("microposts.content")%></strong>
  <%= @micropost.content %>
</p>

<%= link_to I18n.t("actions.edit"), edit_micropost_path(@micropost) %> |
<%= link_to I18n.t("actions.back"), microposts_path %>