internal social network/bt7/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#home'
  resources :static_pages do
    collection do
      get :home
      get :help
    end
  end
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'

  # get 'static_pages/home'
  # get 'static_pages/help'
  resources :microposts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

internal social network/bt7/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

internal social network/bt7/app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
end

internal social network/bt7/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

internal social network/bt7/app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[show edit update destroy]

  # GET /microposts or /microposts.json
  def index
    @content = params[:content]
    @microposts = @content.present? ? Micropost.where(content: @content) : Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show; end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit; end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_micropost
    @micropost = Micropost.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def micropost_params
    params.require(:micropost).permit(:user_id, :content)
  end
end

internal social network/bt7/app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

internal social network/bt7/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Ruby on Rails Tutorial Sample App'
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end

  def displayName
    nam = 'Tran Huu Thang'
  end
end

internal social network/bt7/app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
end

internal social network/bt7/app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

internal social network/bt7/app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "user Id" %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

internal social network/bt7/app/views/microposts/edit.html.erb
<% provide :title, "Edit Micropost" %>

<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

internal social network/bt7/app/views/microposts/index.html.erb
<%=javascript_include_tag('manager/micropost.js') %>

<% provide :title, "Microposts" %>
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th style="margin:10px">User_Id</th>
      <th> Content</th>
      <th> action</th>
    </tr>
  </thead>

  <tbody>
    <div style="justify-content: flex-end; display: flex;"> 
       <input  class="content">
        <a style="background-color: #82b8e6;" href="/microposts" class="btn_search"> search </a>
    </div>
    <% @microposts.each do |micropost| %>
      <tr scope="row">
        <td><%= micropost.user_id %></td>
        <td><%= micropost.content %></td>
        <td >
          <%= link_to 'Show', micropost %>
          <%= link_to 'Edit', edit_micropost_path(micropost) %>
          <%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Micropost', new_micropost_path %>

internal social network/bt7/app/views/microposts/new.html.erb
<% provide :title, "New Micropost" %>

<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

internal social network/bt7/app/views/microposts/show.html.erb
<% provide :title, "Show Micropost" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>UserId:</strong>
  <%= @micropost.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>